### ISSUE TITLE
error installing driver package

### ISSUE THREAD

**Issue by danielpaul-123** [lwfinger/rtw89#395]
using the method to make the .deb package for dkms packaging in ubuntu 24.04. dpkg-buildpackage works, but installing it causes error

Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
Note, selecting 'rtw89-dkms' instead of './rtw89-dkms_1.0.2-3_all.deb'
rtw89-dkms is already the newest version (1.0.2-3).
0 upgraded, 0 newly installed, 0 to remove and 7 not upgraded.
1 not fully installed or removed.
After this operation, 0 B of additional disk space will be used.
Do you want to continue? [Y/n] y
Setting up rtw89-dkms (1.0.2-3) ...
Removing old rtw89-1.0.2 DKMS files...
Deleting module rtw89-1.0.2 completely from the DKMS tree.
Loading new rtw89-1.0.2 DKMS files...
Building for 6.14.0-24-generic
Building initial module for 6.14.0-24-generic
ERROR: Cannot create report: [Errno 17] File exists: '/var/crash/rtw89-dkms.0.crash'
Error! Bad return status for module build on kernel: 6.14.0-24-generic (x86_64)
Consult /var/lib/dkms/rtw89/1.0.2/build/make.log for more information.
dpkg: error processing package rtw89-dkms (--configure):
 installed rtw89-dkms package post-installation script subprocess returned error exit status 10
Errors were encountered while processing:
 rtw89-dkms
E: Sub-process /usr/bin/dpkg returned an error code (1)

the /var/lib/dkms/rtw89/1.0.2/build/make.log

DKMS make.log for rtw89-1.0.2 for kernel 6.14.0-24-generic (x86_64)
Wed Jul 23 08:36:16 PM IST 2025
make: Entering directory '/usr/src/linux-headers-6.14.0-24-generic'
make[1]: Entering directory '/var/lib/dkms/rtw89/1.0.2/build'
warning: the compiler differs from the one used to build the kernel
  The kernel was built by: x86_64-linux-gnu-gcc-13 (Ubuntu 13.3.0-6ubuntu2~24.04) 13.3.0
  You are using:           gcc-13 (Ubuntu 13.3.0-6ubuntu2~24.04) 13.3.0
  CC [M]  core.o
  CC [M]  mac80211.o
  CC [M]  mac.o
  CC [M]  mac_be.o
  CC [M]  phy.o
  CC [M]  phy_be.o
  CC [M]  fw.o
  CC [M]  cam.o
  CC [M]  efuse.o
  CC [M]  efuse_be.o
  CC [M]  regd.o
  CC [M]  sar.o
  CC [M]  coex.o
  CC [M]  ps.o
  CC [M]  chan.o
  CC [M]  debug.o
mac80211.c:1177:35: error: initialization of ‘void (*)(struct ieee80211_hw *, bool)’ {aka ‘void (*)(struct ieee80211_hw *, _Bool)’} from incompatible pointer type ‘void (*)(struct ieee80211_hw *)’ [-Werror=incompatible-pointer-types]
 1177 |         .stop                   = rtw89_ops_stop,
      |                                   ^~~~~~~~~~~~~~
mac80211.c:1177:35: note: (near initialization for ‘rtw89_ops.stop’)
mac80211.c:1216:10: error: ‘const struct ieee80211_ops’ has no member named ‘sta_rc_update’; did you mean ‘link_sta_rc_update’?
 1216 |         .sta_rc_update          = rtw89_ops_sta_rc_update,
      |          ^~~~~~~~~~~~~
      |          link_sta_rc_update
mac80211.c:1216:35: error: initialization of ‘void (*)(struct ieee80211_hw *, struct ieee80211_vif *, struct ieee80211_sta *, bool)’ {aka ‘void (*)(struct ieee80211_hw *, struct ieee80211_vif *, struct ieee80211_sta *, _Bool)’} from incompatible pointer type ‘void (*)(struct ieee80211_hw *, struct ieee80211_vif *, struct ieee80211_sta *, u32)’ {aka ‘void (*)(struct ieee80211_hw *, struct ieee80211_vif *, struct ieee80211_sta *, unsigned int)’} [-Werror=incompatible-pointer-types]
 1216 |         .sta_rc_update          = rtw89_ops_sta_rc_update,
      |                                   ^~~~~~~~~~~~~~~~~~~~~~~
mac80211.c:1216:35: note: (near initialization for ‘rtw89_ops.sta_set_decap_offload’)
cc1: some warnings being treated as errors
make[3]: *** [/usr/src/linux-headers-6.14.0-24-generic/scripts/Makefile.build:207: mac80211.o] Error 1
make[3]: *** Waiting for unfinished jobs....
core.c: In function ‘rtw89_core_napi_init’:
core.c:2591:9: error: implicit declaration of function ‘init_dummy_netdev’ [-Werror=implicit-function-declaration]
 2591 |         init_dummy_netdev(&rtwdev->netdev);
      |         ^~~~~~~~~~~~~~~~~
cc1: some warnings being treated as errors
make[3]: *** [/usr/src/linux-headers-6.14.0-24-generic/scripts/Makefile.build:207: core.o] Error 1
make[2]: *** [/usr/src/linux-headers-6.14.0-24-generic/Makefile:2002: .] Error 2
make[1]: *** [/usr/src/linux-headers-6.14.0-24-generic/Makefile:251: __sub-make] Error 2
make[1]: Leaving directory '/var/lib/dkms/rtw89/1.0.2/build'
make: *** [Makefile:251: __sub-make] Error 2
make: Leaving directory '/usr/src/linux-headers-6.14.0-24-generic'

**Comment by Beagle** [comment]
Having the same issue

**Comment by a5a5aa555oo** [comment]
Try this rtw89 driver: https://github.com/morrownr/rtw89
