### ISSUE TITLE
installing rtw89-dkms_1.0.2-3_all.deb returns error on kernel 6.11.0-19

### ISSUE THREAD

**Issue by scherbicky** [lwfinger/rtw89#378]
```
apt install ../rtw89-dkms_1.0.2-3_all.deb

Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
Note, selecting 'rtw89-dkms' instead of '../rtw89-dkms_1.0.2-3_all.deb'
rtw89-dkms is already the newest version (1.0.2-3).
0 upgraded, 0 newly installed, 0 to remove and 5 not upgraded.
1 not fully installed or removed.
After this operation, 0 B of additional disk space will be used.
Do you want to continue? [Y/n] y
Setting up rtw89-dkms (1.0.2-3) ...
Removing old rtw89-1.0.2 DKMS files...
Deleting module rtw89-1.0.2 completely from the DKMS tree.
Loading new rtw89-1.0.2 DKMS files...
Building for 6.11.0-19-generic
Building initial module for 6.11.0-19-generic
Error! Bad return status for module build on kernel: 6.11.0-19-generic (x86_64)
Consult /var/lib/dkms/rtw89/1.0.2/build/make.log for more information.
dpkg: error processing package rtw89-dkms (--configure):
 installed rtw89-dkms package post-installation script subprocess returned error exit status 10
Errors were encountered while processing:
 rtw89-dkms
E: Sub-process /usr/bin/dpkg returned an error code (1)

```

And make log file:

```
~$ cat /var/lib/dkms/rtw89/1.0.2/build/make.log

DKMS make.log for rtw89-1.0.2 for kernel 6.11.0-19-generic (x86_64)
trešdiena, 2025. gada 12. marts, 06:54:46 EET
make: Entering directory '/usr/src/linux-headers-6.11.0-19-generic'
warning: the compiler differs from the one used to build the kernel
  The kernel was built by: x86_64-linux-gnu-gcc-13 (Ubuntu 13.3.0-6ubuntu2~24.04) 13.3.0
  You are using:           gcc-13 (Ubuntu 13.3.0-6ubuntu2~24.04) 13.3.0
  CC [M]  /var/lib/dkms/rtw89/1.0.2/build/core.o
  CC [M]  /var/lib/dkms/rtw89/1.0.2/build/mac80211.o
  CC [M]  /var/lib/dkms/rtw89/1.0.2/build/mac.o
  CC [M]  /var/lib/dkms/rtw89/1.0.2/build/mac_be.o
  CC [M]  /var/lib/dkms/rtw89/1.0.2/build/phy.o
  CC [M]  /var/lib/dkms/rtw89/1.0.2/build/phy_be.o
  CC [M]  /var/lib/dkms/rtw89/1.0.2/build/fw.o
  CC [M]  /var/lib/dkms/rtw89/1.0.2/build/cam.o
  CC [M]  /var/lib/dkms/rtw89/1.0.2/build/efuse.o
  CC [M]  /var/lib/dkms/rtw89/1.0.2/build/efuse_be.o
  CC [M]  /var/lib/dkms/rtw89/1.0.2/build/regd.o
  CC [M]  /var/lib/dkms/rtw89/1.0.2/build/sar.o
/var/lib/dkms/rtw89/1.0.2/build/mac80211.c:1177:35: error: initialization of ‘void (*)(struct ieee80211_hw *, bool)’ {aka ‘void (*)(struct ieee80211_hw *, _Bool)’} from incompatible pointer type ‘void (*)(struct ieee80211_hw *)’ [-Werror=incompatible-pointer-types]
 1177 |         .stop                   = rtw89_ops_stop,
      |                                   ^~~~~~~~~~~~~~
/var/lib/dkms/rtw89/1.0.2/build/mac80211.c:1177:35: note: (near initialization for ‘rtw89_ops.stop’)
  CC [M]  /var/lib/dkms/rtw89/1.0.2/build/coex.o
  CC [M]  /var/lib/dkms/rtw89/1.0.2/build/ps.o
cc1: some warnings being treated as errors
make[2]: *** [scripts/Makefile.build:244: /var/lib/dkms/rtw89/1.0.2/build/mac80211.o] Error 1
make[2]: *** Waiting for unfinished jobs....
make[1]: *** [/usr/src/linux-headers-6.11.0-19-generic/Makefile:1931: /var/lib/dkms/rtw89/1.0.2/build] Error 2
make: *** [Makefile:224: __sub-make] Error 2
make: Leaving directory '/usr/src/linux-headers-6.11.0-19-generic'
```

**Comment by a5a5aa555oo** [comment]
Larry passed away last year, so this repo is no longer updated.

To make this driver work on your system, you need this [patch](https://github.com/lwfinger/rtw89/pull/366) applied.

**Comment by scherbicky** [comment]
> Larry passed away last year, so this repo is no longer updated.
> 
> To make this driver work on your system, you need this [patch](https://github.com/lwfinger/rtw89/pull/366) applied.

Sad to hear that. Thank you for provided patch.
