### ISSUE TITLE
This repo doesnt work with 6.18.7-76061807-generic kernel.

### ISSUE THREAD

**Issue by IryaAAA** [lwfinger/rtw89#409]
Attempting to build the driver on Pop!_OS using Kernel 6.18.7-76061807-generic. The build fails during the compilation of mac80211.c due to changes in the ieee80211_ops structure in the 6.18 kernel.

To recreate you guys can use these commands

Clone latest master branch.

Run make.

Errors encountered:

core.c: error: implicit declaration of function ‘init_dummy_netdev’. (Note: I was able to bypass this by manually setting ifindex and reg_state, but a formal fix is needed).

mac80211.c: Multiple incompatible-pointer-types errors for .stop, .config, .set_rts_threshold, and .set_antenna.

`mac80211.c:1177:35: error: initialization of ‘void (*)(struct ieee80211_hw *, bool)’ from incompatible pointer type ‘void (*)(struct ieee80211_hw *)’ [-Werror=incompatible-pointer-types]
1177 | .stop = rtw89_ops_stop,`

**Comment by a5a5aa555oo** [comment]
There is a built-in rtw89 driver inside your kernel 6.18 and it is **MUCH** newer than the one here, Doesn't it work for your Wi-Fi device?
