### ISSUE TITLE
Cannot compile in OpenSuse Leap 15.3

### ISSUE THREAD

**Issue by acerv** [lwfinger/rtw89#56]
Hello, I've tried to compile rt89 drivers for OpenSuse Leap 15.3 (kernel 5.3.18-59.24-default
) with the following procedure:
```
  git clone https://github.com/lwfinger/rtw89.git -b v5
  cd rtw89
  make
```

But I've had this error:
```
make -C /lib/modules/5.3.18-59.24-default/build M=/home/andrea/rtw89 modules
make[1]: Entering directory '/usr/src/linux-5.3.18-59.24-obj/x86_64/default'
  CC [M]  /home/andrea/rtw89/core.o
In file included from /home/andrea/rtw89/coex.h:8:0,
                 from /home/andrea/rtw89/core.c:5:
/home/andrea/rtw89/core.h:3383:20: error: redefinition of ‘fsleep’
 static inline void fsleep(unsigned long usecs)
                    ^~~~~~
In file included from /usr/src/linux-5.3.18-59.24/include/linux/iopoll.h:12:0,
                 from /home/andrea/rtw89/core.h:11,
                 from /home/andrea/rtw89/coex.h:8,
                 from /home/andrea/rtw89/core.c:5:
/usr/src/linux-5.3.18-59.24/include/linux/delay.h:69:20: note: previous definition of ‘fsleep’ was here
 static inline void fsleep(unsigned long usecs)
                    ^~~~~~
make[3]: *** [/usr/src/linux-5.3.18-59.24/scripts/Makefile.build:288: /home/andrea/rtw89/core.o] Error 1
make[2]: *** [/usr/src/linux-5.3.18-59.24/Makefile:1675: _module_/home/andrea/rtw89] Error 2
make[1]: *** [../../../linux-5.3.18-59.24/Makefile:179: sub-make] Error 2
make[1]: Leaving directory '/usr/src/linux-5.3.18-59.24-obj/x86_64/default'
make: *** [Makefile:52: all] Error 2

Regards,
Andrea
```

**Comment by lwfinger** [comment]
In Leap 15.3, openSUSE backported kernel API changes from newer kernels. Your build problem thus is something I cannot change without breaking the builds of every user whose distro has not committed what I believe to be a heinous act.

You should delete the code starting at line 3383 that defines fsleep() in file core.h. After it works, do a 'git add core.h && git commit' and add a suitable commit message. By doing that, you will be able to update the other code when it changes without any problems.

**Comment by acerv** [comment]
Thank you very much for you support. Now the code does compile:
```
make -C /lib/modules/5.3.18-59.24-default/build M=/home/andrea/rtw89_second modules
make[1]: Entering directory '/usr/src/linux-5.3.18-59.24-obj/x86_64/default'
  CC [M]  /home/andrea/rtw89_second/core.o
  CC [M]  /home/andrea/rtw89_second/debug.o
  CC [M]  /home/andrea/rtw89_second/mac80211.o
  CC [M]  /home/andrea/rtw89_second/mac.o
  CC [M]  /home/andrea/rtw89_second/phy.o
  CC [M]  /home/andrea/rtw89_second/fw.o
  CC [M]  /home/andrea/rtw89_second/rtw8852a.o
  CC [M]  /home/andrea/rtw89_second/rtw8852a_table.o
  CC [M]  /home/andrea/rtw89_second/rtw8852a_rfk.o
  CC [M]  /home/andrea/rtw89_second/rtw8852a_rfk_table.o
  CC [M]  /home/andrea/rtw89_second/cam.o
  CC [M]  /home/andrea/rtw89_second/efuse.o
  CC [M]  /home/andrea/rtw89_second/regd.o
  CC [M]  /home/andrea/rtw89_second/coex.o
  CC [M]  /home/andrea/rtw89_second/ps.o
  CC [M]  /home/andrea/rtw89_second/sar.o
  CC [M]  /home/andrea/rtw89_second/ser.o
  CC [M]  /home/andrea/rtw89_second/util.o
  LD [M]  /home/andrea/rtw89_second/rtw89core.o
  CC [M]  /home/andrea/rtw89_second/pci.o
  LD [M]  /home/andrea/rtw89_second/rtw89pci.o
  Building modules, stage 2.
  MODPOST 2 modules
  CC      /home/andrea/rtw89_second/rtw89core.mod.o
  LD [M]  /home/andrea/rtw89_second/rtw89core.ko
  CC      /home/andrea/rtw89_second/rtw89pci.mod.o
  LD [M]  /home/andrea/rtw89_second/rtw89pci.ko
make[1]: Leaving directory '/usr/src/linux-5.3.18-59.24-obj/x86_64/default'

```
