### ISSUE TITLE
can not  build in ubuntu20.04

### ISSUE THREAD

**Issue by lernn** [lwfinger/rtw89#390]
![Image](https://github.com/user-attachments/assets/9610d812-2de6-407e-9dc2-ab5bae9242d6)

My wireless module is Realtek RTL8852CE, the system is Ubuntu 20.04, and the kernel version is 5.15.0-46-generic. When I run the make command, I get the following error: rtw89/fw.h:xxx: error: expected specifier-qualifier-list before ‘DECLARE_FLEX_ARRAY’

``
make -C /lib/modules/5.15.0-46-generic/build M=/home/wjw/Desktop/rtw89 modules
make[1]: Entering directory '/usr/src/linux-headers-5.15.0-46-generic'
warning: the compiler differs from the one used to build the kernel
  The kernel was built by: gcc (Ubuntu 9.4.0-1ubuntu1~20.04.1) 9.4.0
  You are using:           gcc (Ubuntu 9.4.0-1ubuntu1~20.04.2) 9.4.0
  CC [M]  /home/wjw/Desktop/rtw89/core.o
In file included from /home/wjw/Desktop/rtw89/core.c:13:
/home/wjw/Desktop/rtw89/fw.h:3220:3: error: expected specifier-qualifier-list before ‘DECLARE_FLEX_ARRAY’

 3220 |   DECLARE_FLEX_ARRAY(u8, raw);
      |   ^~~~~~~~~~~~~~~~~~
make[2]: *** [scripts/Makefile.build:297: /home/wjw/Desktop/rtw89/core.o] Error 1
make[1]: *** [Makefile:1881: /home/wjw/Desktop/rtw89] Error 2
make[1]: Leaving directory '/usr/src/linux-headers-5.15.0-46-generic'
make: *** [Makefile:93: all] Error 2
``

**Comment by a5a5aa555oo** [comment]
[The Linux Community Lost Wireless Pioneer Larry Finger](https://salvacybersec.medium.com/the-linux-community-lost-wireless-pioneer-larry-finger-ff7efd415da7)

So, try this rtw89 driver in my repo.
https://github.com/a5a5aa555oo/rtw89
